name: Build & Test

on: push

env:
  GO_VERSION: "1.14"
  GO111MODULE: on

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./... -timeout=120s

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.29
